@startuml
hide footbox

participant ":AddNoteCommandParser" as Parser #lightgreen
participant ":ParserUtil" as Util #lightblue
participant ":AddNoteCommand" as Command #lightsalmon
participant ":Model" as Model #lightpink
participant ":Person" as Person #lightyellow
participant ":Note" as Note #lightyellow

Parser -> Util : parseIndex(splitArgs[0])
activate Util
Util --> Parser : index
deactivate Util

Parser -> Note : new Note(splitArgs[1].trim())
activate Note
Note --> Parser : note
deactivate Note

Parser -> Command : new AddNoteCommand(index, note)
activate Command
Command --> Parser : command
deactivate Command

-> Command : execute(model)

activate Command
Command -> Model : getFilteredPersonList()
activate Model
Model --> Command : lastShownList
deactivate Model

Command -> Person : addNote(note)
activate Person
Person --> Command
deactivate Person

<-- Command : new CommandResult(MESSAGE_NOTE_SUCCESS)
deactivate Command

@enduml
