@startuml
!include ../style.puml
skinparam arrowThickness 1.1
skinparam arrowColor LOGIC_COLOR_T4
skinparam classBackgroundColor LOGIC_COLOR


class FindExpressionParser {
  +parseToPredicate(tokens: List<Token>): Predicate<Person>
}

interface "<<interface>>\nPredicate<T>" as Predicate

FindExpressionParser --> Predicate : produces >

@enduml
