@startuml
!include ../style.puml
skinparam ArrowFontStyle plain

participant ":UI" as UI
participant ":FindCommandParser" as FCP
participant ":FindFilterStringTokenizer" as Tokenizer
participant ":FindExpressionParser" as Parser

UI -> FCP: parse("n/Alice && (n/Bob || n/Charlie)")
activate FCP

FCP -> Tokenizer: tokenize("n/Alice && (n/Bob || n/Charlie)")
activate Tokenizer

Tokenizer --> FCP: tokensList
deactivate Tokenizer

FCP -> Parser: parseToPredicate(tokensList)
activate Parser

Parser --> FCP: predicateForSearch
deactivate Parser

FCP --> UI: return new FindCommand(predicateForSearch)
deactivate FCP

@enduml
