@startuml
skinparam conditionStyle diamond

start
:User executes Add command;
note :Valid Input Format: \n"add n/NAME p/PHONE e/EMAIL \na/ADDRESS sb/SUBJECT d/DAY \nb/START end/END pr/PAYRATE"
:Checks for duplicate tutees and clashing schedules;
if () then ([Adding this tutee will not \nresult in duplicate tutees or \nclashing schedules]\n)
  :Add tutee to tutee list;

else ([Else]\n)
  :Display error message;
endif

stop

@enduml
