@startuml
!pragma useVerticalIf on
skin rose
skinparam ActivityFontSize 15
skinparam ArrowFontSize 12
start
: User enters "add" command;

if () then ([else])
  :Error: ParseException thrown;
  stop
([All compulsory fields met and correct format]) elseif () then ([Duplicate Card Detected])
    :Error: DuplicateCardException thrown;
    stop
else ([else])
  :Card created successfully ;
endif

stop

@enduml