@startuml
skin rose
skinparam ActivityFontSize 15
skinparam ArrowFontSize 12
start
:User executes command;

'Since the beta syntax does not support placing the condition outside the
'diamond we place it as the true branch instead.

if () then ([command successfully
 executed])
    :Add command string to CommandStringStash;
    :Move currentCmdIndex to right after the
    last element in the CommandStringStash;
else ([else])
endif
stop
@enduml
