@startuml
skin rose
skinparam ActivityFontSize 15
skinparam ArrowFontSize 12
start
:User executes command;

'Since the beta syntax does not support placing the condition outside the
'diamond we place it as the true branch instead.

if (command is successful?) then ([yes])
    :Add command string to CommandStringStash;
    :Move currentCmdIndex to right after the recently added
    command string in the CommandStringStash;
else ([no])
endif
stop
@enduml
