@startuml
skin rose
skinparam ActivityFontSize 15
skinparam ArrowFontSize 12
start
:User executes "importaddressbook" command;

if (Valid Format?) then (Yes)
    :Read Address Book from file;
    :Update Address Book as addressbook.json;
    :Provide Success Feedback;
else (No)
    :Provide Error Feedback;
endif

stop
@enduml
