@startuml
skin rose
skinparam ActivityFontSize 15
skinparam ArrowFontSize 12
start
:User enters input into UI;
:Input is passed to the LogicManager;
:LogicManager sends input to NetworkBookParser;

'Since the beta syntax does not support placing the condition outside the
'diamond we place it as the true branch instead.

switch (Input starts with)
case ( "add", "delete", "create", "filter", "sort", "edit")
    :Parse remaining input with relevant
    Parser and return Command object;
case ( "help", "redo", "undo", "save", "clear", "list", "exit")
    :Return the relevant Command object,
    while ignoring the remaining input;
case ( [prefix not recognized])
    :Throw error to UI to inform user
    that command does not exist;
endswitch

if (Parsing successful?) is (yes) then
  :Execute the command and
  update the status of the Model
  to the user;
else (no)
  :Send the parsing error
  message to UI to inform user;
endif
stop
@enduml
