@startuml
skin rose
skinparam ActivityFontSize 15
skinparam ArrowFontSize 12
start
:User executes add-s command;

'Since the beta syntax does not support placing the condition outside the
'diamond we place it as the true branch instead.

if () then ([valid Index])
    :Get tutor;
    if () then ([valid StartTime and EndTime for schedule])
        :Create new Schedule object;
        if () then ([schedule does not already exists])
            if () then ([schedule does not clash])
                    : Add Schedule;
                else ([else])
                    :Throw Exception;
                endif
        else ([else])
            :Throw  Exception;
        endif
    else ([else])
        :Throw Exception;
    endif
else ([else])
    :Throw Exception;
endif
stop
@enduml
