@startuml
!include style.puml
 skin rose
 skinparam ActivityFontSize 15
 skinparam ArrowFontSize 12

start
:Execute AppendLogCommand;
if () then ([no FindCommand result])
  :Notify user of failure;
else ([has FindCommand result])
  :Save a copy of the current LogBook;
  :Add LogCommand to the command history;
repeat :Retrieve person from FindCommand result;
    if () then ([person is duplicate])
        :Person is added to duplicate clause;
    else ([person is non-duplicate])
        :Person is added to the LogBook;
    endif
repeat while () is ([More persons in FindCommand])
-> [No more persons in FindCommand result];

if () then ([FindCommand contains at least one duplicate])
  :Notify user of duplicate person(s);
else ([FindCommand contains no duplicates])
  :Notify user of success;
endif
endif
stop
@enduml
