@startuml
!include style.puml
skinparam ArrowFontStyle plain

Participant ":PersonListPanel" as panel UI_COLOR
Participant ":PersonCard" as personCardA UI_COLOR
Participant "Alice:Person" as personA MODEL_COLOR
Participant "apptX:Appointment" as appt MODEL_COLOR

[-> panel : updateItem(Alice, false)

Create personCardA
panel -> personCardA : new PersonCard(Alice)

personCardA -> personA : getName()
personA -> personCardA : Alice:Name

personCardA -> personA : getPhone()
personA -> personCardA : 1234:Phone

alt Alice has appointment
    personCardA -> personA : getAppointment()
    personA -> personCardA : apptX
    personCardA -> appt : toString()
    appt -> personCardA
    personCardA -> panel : PersonCard object
    <- panel : end update
else Alice does not have appointment
    personCardA -> personA : getAppointment()
    personA -> personCardA : //null//
    personCardA -> panel : //null//.toString() throws NullPointerException
    <- panel : NullPointerException
end
@enduml
