@startuml
!include style.puml
show members
hide empty members
skinparam classAttributeFontColor #FFFFFF
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

Package Attendance as AttendancePackage <<Rectangle>>{

Class UniqueAttendanceList
Class Attendance
Class Hours
Class Name
Class Remark
}

Class HiddenOutside #FFFFFF
HiddenOutside ..> UniqueAttendanceList

UniqueAttendanceList ..> "*" Attendance
Attendance *---> "Member 1" Name
Attendance *---> "1 Event" Name
Attendance *--> "1" Hours
Attendance *--> "1" Remark

@enduml
