@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

AddressBook *-right-> "1" UniquePersonList
AddressBook *-left-> "1" EventList

UniquePersonList --> "*" Person
EventList --> "*" Event

Person --> "*" Group

Person *-right-> "1" Name
Person *--> "0..1" Phone
Person *--> "0..1" Email
Person *--> "0..1" Address
Person *--> "0..1" Birthday
Person *--> "0..1" Remark

Event *-left-> "1" EventName
Event *--> "1" EventType
Event *--> "1..2" EventDate
Event *--> "0..2" EventTime
Event *--> "*" Group
Event *-> "*" Person
@enduml
