@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

AddressBook *-right-> "1" UniqueList<Person>
AddressBook *-right-> "1" UniqueTagList
UniqueTagList -[hidden]down- UniqueList<Person>
UniqueTagList -[hidden]down- UniqueList<Person>

UniqueTagList -right-> "*" Tag
UniqueList<Person> -right-> Person

Person -up-> "*" Tag

Person *--> Name
Person *--> Phone
Person *--> Email
Person *--> Address
@enduml
