@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR


ManageHr *-right-> "1" UniqueEmployeeList
ManageHr *-right-> "1" UniqueDepartmentList
UniqueDepartmentList -[hidden]down- UniqueEmployeeList
UniqueDepartmentList -[hidden]down- UniqueEmployeeList

UniqueDepartmentList -right-> "*" Department
Department --> "*" EmployeeName
Department *--> DepartmentName
UniqueEmployeeList --> "*" Employee

Employee -up-> "*" DepartmentName
Employee *-left-> Phone
Employee *--> Email
Employee *--> Address
Employee *--> Salary
Employee *--> Leave
Employee *--> Role
Employee *-right-> EmployeeName : name
Employee -right-> "*" EmployeeName : superiors
@enduml
