@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor UI_COLOR_T4
skinparam classBackgroundColor UI_COLOR

package UI <<Rectangle>>{
Class "<<interface>>\nUi" as Ui
Class "{abstract}\nUiPart" as UiPart
Class UiManager
Class MainWindow
Class BottomListPanel
Class EventListPanel
Class TaskListPanel
Class EventCard
Class TaskCard
}

package Model <<Rectangle>> {
Class HiddenModel #FFFFFF
}

package Logic <<Rectangle>> {
Class HiddenLogic #FFFFFF
}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Ui

UiManager .left.|> Ui
UiManager -down-> "1" MainWindow

MainWindow *-down-> "1" BottomListPanel

BottomListPanel -down-> "0..1" TaskListPanel
BottomListPanel -down-> "0..1" EventListPanel
note left on link
{XOR}
end note

EventListPanel -down-> "*" EventCard
TaskListPanel -down-> "*" TaskCard


MainWindow -left-|> UiPart

TaskListPanel --|> UiPart
EventListPanel --|> UiPart
TaskCard --|> UiPart
EventCard --|> UiPart
BottomListPanel --|> UiPart

EventCard ..> Model
TaskCard ..> Model
UiManager -right-> Logic
MainWindow -left-> Logic

MainWindow -[hidden]-|> UiPart
@enduml
