@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor LOGIC_COLOR_T4
skinparam classBackgroundColor LOGIC_COLOR

package Trackers as TrackerPackage {
Class "<<interface>>\nTracker" as Tracker
Class Tracker
Class AttendanceTracker
Class AssignmentTracker
Class ClassParticipationTracker
}

AttendanceTracker .up.|> Tracker
AssignmentTracker .up.|> Tracker
ClassParticipationTracker .up.|> Tracker

AttendanceTracker --* ClassDetails
AssignmentTracker --* ClassDetails
ClassParticipationTracker --* ClassDetails

@enduml