@startuml

actor User
participant ClearLogCommand
participant Model
participant LogBook

User -> ClearLogCommand: execute()
activate ClearLogCommand

ClearLogCommand -> Model: addToHistory(this)
activate Model
Model --> ClearLogCommand: Command added to history
deactivate Model

ClearLogCommand -> Model: setLogBook(new LogBook())
activate Model
Model -> LogBook: create LogBook
activate LogBook
LogBook -> Model : LogBook created
deactivate LogBook
Model --> ClearLogCommand: Updated logBook with an empty LogBook
deactivate Model

ClearLogCommand -> User: Return CommandResult (Success)
deactivate ClearLogCommand

@enduml
