@startuml
!include style.puml
skinparam ClassFontColor #000000
skinparam ClassBorderColor #000000
skinparam ClassBackgroundColor #FFFFAA
skinparam ClassFontColor<<Hide>> #FFFFFF
skinparam ClassBorderColor<<Hide>> #FFFFFF
skinparam ClassBackgroundColor<<Hide>> #FFFFFF

title User gets the next method

package "User presses ↑ until the first command" <<Rectangle>>{
    package CommandHistory as AFTER <<Rectangle>>{
        class State1 as "<u>command0:String</u>"
        class State2 as "<u>command1:String</u>"
        class State3 as "<u>command2:String</u>"
    }
    class Pointer1 as "Current Command" #FFFFFF
}

package "After pressing ↓" <<Rectangle>>{
    package CommandHistory as AFTER <<Rectangle>>{
        class State4 as "<u>command0:String</u>"
        class State5 as "<u>command1:String</u>"
        class State6 as "<u>command2:String</u>"
    }
    class Pointer2 as "Current Command" #FFFFFF
}
State1 -[hidden]right-> State2
State2 -[hidden]right-> State3

State4 -[hidden]right-> State5
State5 -[hidden]right-> State6
Pointer1 -up-> State1
Pointer2 -up-> State5
@end
