@startuml
!include style.puml
skinparam ClassFontColor #000000
skinparam ClassBorderColor #000000
skinparam ClassBackgroundColor #FFFFAA
skinparam ClassFontColor<<Hide>> #FFFFFF
skinparam ClassBorderColor<<Hide>> #FFFFFF
skinparam ClassBackgroundColor<<Hide>> #FFFFFF

title User enters the first command

package CommandHistory{
    class State1 as "<u>command0:String</u>"
    class State2 as "<u>command1:String</u>" <<Hide>>
    class State3 as "<u>command2:String</u>" <<Hide>>
}
State1 -[hidden]right-> State2
State2 -[hidden]right-> State3

class Pointer as "Current Command" #FFFFFF
Pointer -up-> State2
@end
