@startuml
skin rose
skinparam ActivityFontSize 15
skinparam ArrowFontSize 12
start
:User enters a complete command;

:CompleteCommandParser parses the user input and checks validity;


'Since the beta syntax does not support placing the condition outside the
'diamond we place it as the true branch instead.

switch ()
case([the complete command is valid])
    : Creates a CompleteCommand which is executed by LogicManager;
    switch ()
          case ([user inputs an index])
            : Checks for appointment of given person in FilterPersonList;
            switch ()
            case([if person has existing appointment])
            : Clears appointment for the Person;
            case([if person has no existing appointment])
            : Throws an error;
            endswitch
          case ([user inputs a date])
            : Checks for persons in FilterPersonList who appointment date matches input date;
            switch()
            case([have at least one match])
            : Clears all appointments with matching dates;
            case([has no matches])
            : Throws an error;
            endswitch
        endswitch
case([else])
    : Throws an error;
endswitch
stop
@enduml

