@startuml
!include style.puml
skinparam ArrowFontStyle plain

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":AddressBookParser" as AddressBookParser LOGIC_COLOR
participant ":DeleteMemberCommandParser" as DeleteMemberCommandParser LOGIC_COLOR
participant "d:DeleteCommand" as DeleteCommand LOGIC_COLOR
participant ":CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
end box

[-> LogicManager : execute("delm 1")
activate LogicManager

LogicManager -> AddressBookParser : parseCommand("delm 1")
activate AddressBookParser

create DeleteMemberCommandParser
AddressBookParser -> DeleteMemberCommandParser
activate DeleteMemberCommandParser

DeleteMemberCommandParser --> AddressBookParser
deactivate DeleteMemberCommandParser

AddressBookParser -> DeleteMemberCommandParser : parse("1")
activate DeleteMemberCommandParser

create DeleteCommand
DeleteMemberCommandParser -> DeleteCommand
activate DeleteCommand

DeleteCommand --> DeleteMemberCommandParser : d
deactivate DeleteCommand

DeleteMemberCommandParser --> AddressBookParser : d
deactivate DeleteMemberCommandParser
'Hidden arrow to position the destroy marker below the end of the activation bar.
DeleteMemberCommandParser -[hidden]-> AddressBookParser
destroy DeleteMemberCommandParser

AddressBookParser --> LogicManager : d
deactivate AddressBookParser

LogicManager -> DeleteCommand : execute()
activate DeleteCommand

DeleteCommand -> Model : deleteMember(1)
activate Model

Model --> DeleteCommand
deactivate Model

create CommandResult
DeleteCommand -> CommandResult
activate CommandResult

CommandResult --> DeleteCommand
deactivate CommandResult

DeleteCommand --> LogicManager : result
deactivate DeleteCommand

[<--LogicManager
deactivate LogicManager
@enduml
