@startuml
skin rose
skinparam ActivityFontSize 15
skinparam ArrowFontSize 13
start
:User requests to remove shortcuts;

'Since the beta syntax does not support placing the condition outside the
'diamond we place it as the true branch instead.
if () then ([Request parsed successfully])
if () then ([Shortcuts are mapped])
    :Remove shortcuts;
else ([else])
    :Notify user shortcut does not exist;
endif
else ([else])
    :Show error and usage message;
endif

stop
@enduml
