@startuml
skin rose
skinparam ActivityFontSize 15
skinparam ArrowFontSize 12
start
:User executes command;

'Since the beta syntax does not support placing the condition outside the
 'diamond we place it as the true branch instead.

if () then ([have index])
    if() then ([numeric index])
        if () then ([index within range])
            :Delete schedule in Addressbook;
        else ([else])
         :ErrorInvalidScheduleDisplayedIndex;
        endif
    else ([else])
     :ErrorInvalidCommandFormat;
    endif
else ([else])
 :ErrorInvalidCommandFormat;
endif
stop
@enduml
