@startuml
!include style.puml
skinparam ArrowFontStyle plain

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":AddressBookParser" as AddressBookParser LOGIC_COLOR
participant ":DeleteCommandParser" as DeleteCommandParser LOGIC_COLOR
participant "d:DeleteCommand" as DeleteCommand LOGIC_COLOR
participant ":CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
end box

[-> LogicManager : execute("delete n/John Doe")
activate LogicManager

LogicManager -> AddressBookParser : parseCommand("delete n/John Doe")
activate AddressBookParser

AddressBookParser -> DeleteCommandParser : parse("delete n/John Doe")
activate DeleteCommandParser

Create DeleteCommand
DeleteCommandParser -> DeleteCommand
activate DeleteCommand

DeleteCommand --> DeleteCommandParser : d
deactivate DeleteCommand

DeleteCommandParser --> AddressBookParser : d
deactivate DeleteCommandParser

AddressBookParser --> LogicManager : d
deactivate AddressBookParser

LogicManager -> DeleteCommand : execute()
activate DeleteCommand

DeleteCommand -> Model : getFilteredPersonList()
activate Model

Model --> DeleteCommand : list
deactivate Model

DeleteCommand -> Model : findPersonByName("John Doe")
activate Model

Model --> DeleteCommand : person
deactivate Model

DeleteCommand -> Model : deletePerson(person)
activate Model

Model --> DeleteCommand
deactivate Model

DeleteCommand -> Model : addToHistory(this)
activate Model

Model --> DeleteCommand
deactivate Model

DeleteCommand -> CommandResult : success
activate CommandResult

CommandResult --> DeleteCommand
deactivate CommandResult

DeleteCommand --> LogicManager : result
deactivate DeleteCommand

<-- LogicManager
deactivate LogicManager

@enduml
