@startuml
'https://plantuml.com/activity-diagram-beta

start
:User wants to delete a group or contact;
:User runs the "delete" command;
if () then ([Invalid command format])
:ProjectPRO throws an error;
else (["delete g/GROUPNAME" or "delete n/NAME"])
:ProjectPRO checks if User is deleting a group or contact;
if () then (["delete g/GROUPNAME"])
:ProjectPRO checks if group exists;
    if () then ([Group exists])
    : ProjectPRO deletes specified group;
    else([Else])
    : ProjectPRO throws an error;
    endif
else(["delete n/NAME"])
: ProjectPRO checks if contact exists;
    if () then ([Contact exists])
    : ProjectPRO deletes specified contact;
    else([Else])
    : ProjectPRO throws an error;
    endif
endif
endif
stop

@enduml
