@startuml
!include style.puml
skinparam ArrowFontStyle plain

Participant ":Logic" as logic LOGIC_COLOR
Participant ":NetworkBookParser" as networkBookParser LOGIC_COLOR
Participant ":EditCommandParser" as editCommandParser LOGIC_COLOR_T1
Participant ":EditAction" as editAction LOGIC_COLOR_T1
Participant ":EditCommand" as editCommand LOGIC_COLOR_T1
Participant ":EditPersonDescriptor" as editPersonDescriptor LOGIC_COLOR_T1
Participant ":Model" as model MODEL_COLOR

-> logic : execute("edit" + details)
activate logic LOGIC_COLOR

logic -> networkBookParser : "edit" + details
activate networkBookParser LOGIC_COLOR

create editCommandParser
networkBookParser -> editCommandParser
activate editCommandParser LOGIC_COLOR_T1

editCommandParser --> networkBookParser
deactivate editCommandParser

networkBookParser -> editCommandParser : parse(details)
activate editCommandParser LOGIC_COLOR_T1

create editAction
editCommandParser -> editAction : generateAction
activate editAction LOGIC_COLOR_T1

editAction --> editCommandParser : action
deactivate editAction

create editCommand
editCommandParser -> editCommand : new EditCommand(index, action)
activate editCommand LOGIC_COLOR_T1

editCommand --> editCommandParser : editCommand
deactivate editCommand

editCommandParser --> networkBookParser : editCommand
deactivate editCommandParser

networkBookParser --> logic : editCommand
deactivate networkBookParser

logic -> editCommand: execute(model)
activate editCommand LOGIC_COLOR_T1

editCommand -> model : get p at index
activate model MODEL_COLOR

model --> editCommand : p at index
deactivate model

create editPersonDescriptor
editCommand -> editPersonDescriptor: person
activate editPersonDescriptor LOGIC_COLOR_T1

editPersonDescriptor --> editCommand : editPersonDescriptor
deactivate editPersonDescriptor

editCommand -> editAction : edit(editPersonDescriptor)
activate editAction LOGIC_COLOR_T1

editAction -> editPersonDescriptor : modify field

editAction --> editCommand
deactivate editAction

editCommand -> editPersonDescriptor : toPerson()
activate editPersonDescriptor LOGIC_COLOR_T1

editPersonDescriptor --> editCommand : new person
deactivate editPersonDescriptor

editCommand -> model : old p -> new p
editCommand -> model : update list

editCommand --> logic : command success
deactivate editCommand

<-- logic : command success

@enduml
