@startuml
skinparam ActivityFontSize 15
skinparam ArrowFontSize 12
!pragma useVerticalIf on
start
:User executes edit command;
:Parse command string;

if () then ([else])
    :ParseException: INVALID_COMMAND_FORMAT;
    stop
([valid command format]) elseif () then ([wrong attribute format])
    :ParseException: CONSTRAINTS;
    stop
([else]) elseif () then ([invalid index])
    :ParseException: INVALID_PERSON_DISPLAYED_INDEX;
    stop
([else]) elseif () then ([edit empty additional attribute])
    :CommandException: USE_ADDALT_COMMAND;
    stop
([else]) elseif () then ([same primary and secondary email after edit])
    :CommandException: DUPLICATE_EMAIL;
    stop
([else]) elseif () then ([no change after edit])
    :CommandException: NO_CHANGE;
    stop
else ([else])
endif
:Update person in contact list with edited attributes;
:Show EDIT_PERSON_SUCCESS message;

stop
@enduml
