@startuml
skin rose
skinparam ActivityFontSize 15
skinparam ArrowFontSize 12
skinparam defaultTextAlignment center

start
:User executes editb command;
:Parse the input parameters;

'Since the beta syntax does not support placing the condition outside the
'diamond we place it as the true branch instead.

if () then ([input is invalid])
    :Show corresponding error message;
else ([else])
    if () then ([New name clashes with existing band])
        :Error: Duplicate Band!;

    else ([else])
        :Edit Band Successfully;
    endif

endif

stop
@enduml