@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":AddressBookParser" as AddressBookParser LOGIC_COLOR
participant ":EditLeaveCommandParser" as EditLeaveCommandParser LOGIC_COLOR
participant "r:EditLeaveCommand" as EditLeaveCommand LOGIC_COLOR
participant ":CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
end box
[-> LogicManager : execute("editleave id/EID1234-5678 old/2023-11-01 new/2023-11-02")
activate LogicManager

LogicManager -> AddressBookParser : parseCommand("editleave id/EID1234-5678 old/2023-11-01 new/2023-11-02")
activate AddressBookParser

create EditLeaveCommandParser
AddressBookParser -> EditLeaveCommandParser
activate EditLeaveCommandParser

EditLeaveCommandParser --> AddressBookParser
deactivate EditLeaveCommandParser

AddressBookParser -> EditLeaveCommandParser : parse("id/EID1234-5678 old/2023-11-01 new/2023-11-02")
activate EditLeaveCommandParser

create EditLeaveCommand
EditLeaveCommandParser -> EditLeaveCommand
activate EditLeaveCommand

EditLeaveCommand --> EditLeaveCommandParser : r
deactivate EditLeaveCommand

EditLeaveCommandParser --> AddressBookParser : r
deactivate EditLeaveCommandParser

EditLeaveCommandParser -[hidden]-> AddressBookParser
destroy EditLeaveCommandParser

AddressBookParser --> LogicManager : r
deactivate AddressBookParser

LogicManager -> EditLeaveCommand : execute()
activate EditLeaveCommand

EditLeaveCommand -> Model : setEmployee(targetEmployee, editedEmployee)
activate Model

Model --> EditLeaveCommand

EditLeaveCommand -> Model : updateFilteredEmployeeList()

Model --> EditLeaveCommand
deactivate Model

create CommandResult
EditLeaveCommand -> CommandResult
activate CommandResult

CommandResult --> EditLeaveCommand
deactivate CommandResult

EditLeaveCommand --> LogicManager : result
deactivate EditLeaveCommand

[<--LogicManager
deactivate LogicManager
@enduml
