@startuml
skin rose
skinparam ActivityFontSize 15
skinparam ArrowFontSize 12
start
:User creates a visual representation;
:User executes export command;
:User indicates the filepath to save the image exported;
:Exported image is saved to the chosen location;
stop
@enduml
