@startuml
'https://plantuml.com/activity-diagram-beta
skin rose
skinparam ActivityFontSize 15
skinparam ArrowFontSize 12
|User|
start
:Start JABPro;
:Enter export command;
if (CommandIsSuccessful) then (true)
  |JABPro|
  :Exports existing data to /data/export.csv;
else (false)
  |JABPro|
  :Display error message and provide remedy;
  |User|

endif

stop

@enduml
