@startuml
skin rose
skinparam ActivityFontSize 15
skinparam ArrowFontSize 12
start
:User launches LoveBook;

: User enters a command to filter dates in the GUI;

: Input is passed over to the logic component;

if () then ([command format is valid])
        if () then ([all fields contain valid values])
            if () then ([date with same name does not exist])
                :Save date to LoveBook;
                :Display success message;
                stop
            else ([else])
                :Display date already exists error message;
                stop
            endif
        else ([else])
            :Display invalid field value error message;
            stop
        endif
else ([else])
    :Display invalid command format error message;
    stop
endif
@enduml
