@startuml
'https://plantuml.com/activity-diagram-beta

start
:User enters filter command syntax;
:ApplicantBookParser and FilterCommandParser
parse arguments;
if (At least 1 argument is provided) then (true)
  :Parse provided fields;
  if (Provided fields are valid) then (true)
      :Create new CustomFilterPredicate
      from specified fields;
      :Create new FilterCommand
      from CustomFilterPredicate;
      :FilterCommand updates predicate used in
      ModelManager with CustomFilterPredicate;
      :Display success message and show updated list in GUI;
      stop
  else (false)
  :Throw ParseException with
        invalid command format
        message and proper Filter
        syntax;
        :Display error message;
        stop
    endif

else (false)
label 1
label 2
label 3

:Throw ParseException with
      invalid command format
      message and proper Filter
      syntax;
      :Display error message;
      stop
endif

@enduml

