@startuml
skin rose
skinparam ActivityFontSize 15
skinparam ArrowFontSize 12
start
:User enters filter command;

'Since the beta syntax does not support placing the condition outside the
'diamond we place it as the true branch instead.

if () then ([All fields are valid])
    :Filter is applied;
else ([else])
:Parse Exception is thrown;
endif
stop
@enduml