@startuml
'https://plantuml.com/sequence-diagram

!include style.puml
skinparam ArrowFontStyle plain

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":AddressBookParser" as AddressBookParser LOGIC_COLOR
participant ":ImportCommandParser" as ImportCommandParser LOGIC_COLOR
participant "i:ImportCommand" as ImportCommand LOGIC_COLOR
participant ":CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
participant ":AddressBook" as AddressBook MODEL_COLOR
participant "s:Student" as Student MODEL_COLOR
end box

[-> LogicManager : execute("import student_data.csv")
activate LogicManager

LogicManager -> AddressBookParser : parseCommand("import student_data.csv")
activate AddressBookParser

create ImportCommandParser
AddressBookParser -> ImportCommandParser
activate ImportCommandParser

ImportCommandParser --> AddressBookParser
deactivate ImportCommandParser

AddressBookParser -> ImportCommandParser : parse("student_data.csv")
activate ImportCommandParser

loop [line != null]
ImportCommandParser -> ImportCommandParser: parseStudentFromCsv(attributes)
activate ImportCommandParser
create Student
ImportCommandParser -> Student
activate Student
return
return s
end

create ImportCommand
ImportCommandParser -> ImportCommand
activate ImportCommand

ImportCommand --> ImportCommandParser : i
deactivate ImportCommand

ImportCommandParser --> AddressBookParser : i
deactivate ImportCommandParser
'Hidden arrow to position the destroy marker below the end of the activation bar.
ImportCommandParser -[hidden]-> AddressBookParser
destroy ImportCommandParser

AddressBookParser --> LogicManager : i
deactivate AddressBookParser

LogicManager -> ImportCommand : execute()
activate ImportCommand

loop for each Student
opt not hasPerson
ImportCommand -> Model : addPerson(s)
activate Model
Model -> AddressBook : addPerson(s)
activate AddressBook
AddressBook --> Model
deactivate AddressBook
Model --> ImportCommand
deactivate Model
end
end


create CommandResult
ImportCommand -> CommandResult
activate CommandResult

CommandResult --> ImportCommand
deactivate CommandResult

ImportCommand --> LogicManager : result
deactivate ImportCommand

[<--LogicManager
deactivate LogicManager
@enduml
