@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR_T4
skinparam classBackgroundColor MODEL_COLOR
skinparam classAttributeIconSize 0
Package Interaction as ModelPackage <<Rectangle>>{
class Interaction {
<color: #FFFFFF>- Date: date
<color: #FFFFFF>- String: interactionNote
}
class "<<enum>>\nOutcome" as Outcome {
        CLOSED
        INTERESTED
        NOT_INTERESTED
        FOLLOWUP_REQUIRED
        UNKNOWN
}

show Interaction fields
show Outcome members

Interaction *--> "1" Outcome
hide empty methods
}
@enduml
