@startuml
'https://plantuml.com/activity-diagram-beta
skin rose
skinparam ActivityFontSize 15
skinparam ArrowFontSize 12
|User|
skin rose
skinparam ActivityFontSize 15
skinparam ArrowFontSize 12
start
:Start JABPro;
:Enter addL/addG command;
if () then ([Command executed successfully])
  |JABPro|
  :Add username to candidates existing details;
  |User|
  :Enter linkedin/github command;
  |JABPro|
  :Redirect user to page of the social profile;
  |User|
else ([Command execution failed])
  |JABPro|
  :Display error message and provide remedy;
  |User|

endif

stop

@enduml
