@startuml
'https://plantuml.com/activity-diagram-beta
|User|
start
:Start JABPro;
:Enter addL/addG command;
if (CommandIsSuccessful) then ([true])
  |JABPro|
  :Add username to candidates existing details;
  |User|
  :Enter linkedin/github command;
  |JABPro|
  :Redirect user to page of the social profile;
  |User|
else ([false])
  |JABPro|
  :Display error message and provide remedy;
  |User|

endif

stop

@enduml
