@startuml
!include style.puml
skinparam ArrowFontStyle plain


box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":AddressBookParser" as AddressBookParser LOGIC_COLOR
participant ":ListCommandParser" as ListCommandParser LOGIC_COLOR
participant "f:ListCommand" as ListCommand LOGIC_COLOR
participant ":CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
end box

[-> LogicManager : execute("list so/name")
activate LogicManager

LogicManager -> AddressBookParser : parseCommand("list so/name")
activate AddressBookParser

create ListCommandParser
AddressBookParser -> ListCommandParser
activate ListCommandParser

ListCommandParser --> AddressBookParser
deactivate ListCommandParser

AddressBookParser -> ListCommandParser : parse("list so/name")
activate ListCommandParser

create ListCommand
ListCommandParser -> ListCommand : listCommand(sortingComparator)
activate ListCommand

ListCommand --> ListCommandParser : f
deactivate ListCommand

ListCommandParser --> AddressBookParser : f
deactivate ListCommandParser
'Hidden arrow to position the destroy marker below the end of the activation bar.
ListCommandParser -[hidden]-> AddressBookParser
destroy ListCommandParser

AddressBookParser --> LogicManager : f
deactivate AddressBookParser

LogicManager -> ListCommand  : execute()
activate ListCommand

ListCommand -> Model : sortPersonList(sortingComparator)
activate Model

Model --> ListCommand
deactivate Model

ListCommand -> Model : updateFilteredPersonList(PREDICATE_SHOW_ALL_PERSONS)
activate Model

Model --> ListCommand
deactivate Model

create CommandResult
ListCommand -> CommandResult
activate CommandResult

CommandResult --> ListCommand
deactivate CommandResult

ListCommand --> LogicManager : result
deactivate ListCommand



[<--LogicManager
deactivate LogicManager



@enduml
