@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor LOGIC_COLOR_T4
skinparam classBackgroundColor LOGIC_COLOR

package Logic as LogicPackage {

Class AddressBookParser
Class XYZCommand
Class ABCCommand
Class CommandResult
Class "{abstract}\nUndoableCommand" as UndoableCommand
Class "{abstract}\nCommand" as Command


Class "<<interface>>\nLogic" as Logic
Class LogicManager
}

package Model {
Class HiddenModel #FFFFFF
}

package Storage {
}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Logic

LogicManager .right.|> Logic
LogicManager -right->"1" AddressBookParser
AddressBookParser ..> ABCCommand : creates >
AddressBookParser ...> XYZCommand :  creates >

UndoableCommand -up-|> Command
ABCCommand -up-|> UndoableCommand
XYZCommand -up-|> Command
LogicManager .left.> Command : executes >

LogicManager --> Model
LogicManager --> Storage
Storage --[hidden] Model
Command .[hidden]up.> Storage
Command .right.> Model
note bottom of XYZCommand: XYZCommand = ListCommand, \nHelpCommand, etc
note bottom of ABCCommand: ABCCommand = AddCommand, \nDeleteCommand, etc

Logic ..> CommandResult
LogicManager .down.> CommandResult
Command .up.> CommandResult : produces >
@enduml
