@startuml
actor User
participant LogCommand
participant Model
participant LogBook

User -> LogCommand: execute()
activate LogCommand

alt Results from FindCommand not empty
    LogCommand -> Model: getFoundPersonsList()
    activate Model
    Model --> LogCommand: List of found persons
    LogCommand -> LogBook: setPersons(foundPersonsList)
    activate LogBook
    LogBook --> LogCommand: Updated logbook
    deactivate LogBook
    LogCommand -> Model: addToHistory(LogCommand)
    Model --> LogCommand: Command added to history
    LogCommand -> User: Return CommandResult (Success)
else Results from FindCommand are empty
    LogCommand -> User: Throw CommandException
    User --> LogCommand: Handle CommandException
end

deactivate Model
deactivate LogCommand
@enduml
