@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

Package Model as ModelPackage <<Rectangle>>{
Class "<<interface>>\nReadOnlyManageHr" as ReadOnlyManageHr
Class "<<interface>>\nReadOnlyUserPrefs" as ReadOnlyUserPrefs
Class "<<interface>>\nModel" as Model
Class ManageHr
Class ModelManager
Class UserPrefs

Class UniqueEmployeeList
Class UniqueDepartmentList
Class Employee
Class Role
Class Address
Class Email
Class EmployeeName
Class Phone
Class Salary
Class Leave
Class Department
Class DepartmentName

Class I #FFFFFF
}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Model

ManageHr .up.|> ReadOnlyManageHr

ModelManager .up.|> Model
Model .right.> ReadOnlyUserPrefs
Model .left.> ReadOnlyManageHr
ModelManager -left-> "1" ManageHr
ModelManager -[hidden]-> ManageHr
ModelManager -right-> "1" UserPrefs
UserPrefs .up.|> ReadOnlyUserPrefs

ManageHr *--> "1" UniqueEmployeeList
ManageHr *--> "1" UniqueDepartmentList
UniqueDepartmentList --> "~* all" Department
Department *--> DepartmentName
Department --> "*" EmployeeName
UniqueEmployeeList -left-> "~* all" Employee

Employee -right-> "*" EmployeeName : supervisors
Employee *-right-> EmployeeName : name
Employee *--> Phone
Employee *--> Role
Employee *--> Email
Employee *--> Address
Employee *--> Salary
Employee *--> Leave
Employee *--> "*" DepartmentName

Employee -[hidden]up--> I
UniqueEmployeeList -[hidden]right-> I

Phone -[hidden]right-> Address
Address -[hidden]right-> Email

UniqueEmployeeList -[hidden]-> Employee
ModelManager --> "*" Employee : filtered
@enduml
