@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

Package Model as ModelPackage <<Rectangle>>{
Class "<<interface>>\nReadOnlyAddressBook" as ReadOnlyAddressBook
Class "<<interface>>\nReadOnlyUserPrefs" as ReadOnlyUserPrefs
Class "<<interface>>\nModel" as Model
Class AddressBook
Class ModelManager
Class UserPrefs

Class UniqueMusicianList
Class Musician
Class Instrument
Class Email
Class Name
Class Phone
Class Tag
Class "Genre" as g1

Class UniqueBandList
Class Band
Class "Name" as bandname
Class "Genre" as g2

Class I #FFFFFF
}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Model

AddressBook .up.|> ReadOnlyAddressBook

ModelManager .up.|> Model
Model .right.> ReadOnlyUserPrefs
Model .left.> ReadOnlyAddressBook
ModelManager -left-> "1" AddressBook
ModelManager -right-> "1" UserPrefs
UserPrefs .up.|> ReadOnlyUserPrefs

AddressBook *--> "1" UniqueMusicianList
UniqueMusicianList --> "~* all" Musician
Musician *--> Name
Musician *--> Phone
Musician *--> Email
Musician *--> "*" Instrument
Musician *--> "*" Tag
Musician *--> "*" g1

AddressBook *--> "1" UniqueBandList
UniqueBandList --> "~* all" Band
Band *--> bandname
Band *--> "*" g2

Musician -[hidden]up--> I
Band -[hidden]up--> I
UniqueMusicianList -[hidden]right-> I
UniqueBandList -[hidden]right-> I
Musician -[hidden]up--> UniqueMusicianList

Name -[hidden]right-> Phone
Phone -[hidden]right-> Email
Email -[hidden]right-> Tag
Tag -[hidden]right-> Instrument
Instrument -[hidden]right-> g1

ModelManager --> "~* filtered" Musician
ModelManager --> "~* filtered" Band
@enduml
