@startuml
!include style.puml
skinparam ArrowFontStyle plain

Participant ":Logic" as logic LOGIC_COLOR
Participant ":NetworkBookParser" as networkBookParser LOGIC_COLOR
Participant ":OpenLinkCommandParser" as openLinkCommandParser LOGIC_COLOR_T1
Participant ":OpenLinkCommand" as openLinkCommand LOGIC_COLOR_T1
Participant ":Model" as model MODEL_COLOR

-> logic : execute("open" + details)
activate logic LOGIC_COLOR

logic -> networkBookParser : "open" + details
activate networkBookParser LOGIC_COLOR

create openLinkCommandParser
networkBookParser -> openLinkCommandParser
activate openLinkCommandParser LOGIC_COLOR_T1

openLinkCommandParser --> networkBookParser
deactivate openLinkCommandParser

networkBookParser -> openLinkCommandParser : parse(details)
activate openLinkCommandParser LOGIC_COLOR_T1

create openLinkCommand
openLinkCommandParser -> openLinkCommand : personIndex, linkIndex
activate openLinkCommand LOGIC_COLOR_T1

openLinkCommand --> openLinkCommandParser : openLinkCommand
deactivate openLinkCommand

openLinkCommandParser --> networkBookParser : openLinkCommand
deactivate openLinkCommandParser

networkBookParser --> logic : openLinkCommand
deactivate networkBookParser

logic -> openLinkCommand: execute(model)
activate openLinkCommand LOGIC_COLOR_T1

openLinkCommand -> model: openLink(personIndex, linkIndex)
activate model MODEL_COLOR

model --> openLinkCommand: link opened
deactivate model

openLinkCommand --> logic : command success
deactivate openLinkCommand

<-- logic : command success

@enduml
