@startuml
!include style.puml
skinparam ArrowFontStyle plain

box Logic LOGIC_COLOR_T1
Participant ":Logic" as logic LOGIC_COLOR
Participant ":NetworkBookParser" as networkBookParser LOGIC_COLOR
Participant ":OpenLinkCommandParser" as openLinkCommandParser LOGIC_COLOR
Participant ":OpenLinkCommand" as openLinkCommand LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
Participant ":Model" as model MODEL_COLOR
end box

-> logic : execute("open" + details)
activate logic

logic -> networkBookParser : "open" + details
activate networkBookParser

create openLinkCommandParser
networkBookParser -> openLinkCommandParser
activate openLinkCommandParser

openLinkCommandParser --> networkBookParser
deactivate openLinkCommandParser

networkBookParser -> openLinkCommandParser : parse(details)
activate openLinkCommandParser

create openLinkCommand
openLinkCommandParser -> openLinkCommand : personIndex, linkIndex
activate openLinkCommand

openLinkCommand --> openLinkCommandParser : openLinkCommand
deactivate openLinkCommand

openLinkCommandParser --> networkBookParser : openLinkCommand
deactivate openLinkCommandParser

networkBookParser --> logic : openLinkCommand
deactivate networkBookParser

logic -> openLinkCommand: execute(model)
activate openLinkCommand

openLinkCommand -> model: openLink(personIndex, linkIndex)
activate model

model --> openLinkCommand: link opened
deactivate model

openLinkCommand --> logic : command success
deactivate openLinkCommand

<-- logic : command success
deactivate logic

@enduml
