@startuml
!include style.puml
skinparam ArrowFontStyle plain

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":ScheduleCommandParser" as ScheduleCommandParser LOGIC_COLOR
participant "s:ScheduleCommand" as ScheduleCommand LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
participant ":UniqueAppointmentList" as UniqueAppointmentList MODEL_COLOR
participant ":Appointment" as Appointment MODEL_COLOR
end box

[-> LogicManager : execute(schedule n/John ...)
activate LogicManager

LogicManager -> ScheduleCommandParser : parseCommand(schedule n/John ...)
activate ScheduleCommandParser

create ScheduleCommand
ScheduleCommandParser -> ScheduleCommand
activate ScheduleCommand

ScheduleCommand -> Appointment
activate Appointment

Appointment -> Appointment: Appointment(Name...)


Appointment --> ScheduleCommand
deactivate Appointment


ScheduleCommand --> ScheduleCommandParser
deactivate ScheduleCommand

ScheduleCommandParser --> LogicManager : s
deactivate ScheduleCommandParser

LogicManager -> ScheduleCommand : execute()
activate ScheduleCommand

ScheduleCommand -> Model : execute()
activate Model

Model -> UniqueAppointmentList : hasOverlappingAppointments(Appointment appt)
activate UniqueAppointmentList

UniqueAppointmentList -> UniqueAppointmentList : hasOverlapsWith(Appointment appt)

UniqueAppointmentList --> Model
deactivate UniqueAppointmentList

Model --> ScheduleCommand
deactivate Model

ScheduleCommand --> LogicManager : result
deactivate ScheduleCommand

ScheduleCommand -[hidden]-> LogicManager : result
destroy ScheduleCommand

[<--LogicManager
deactivate LogicManager


@enduml
