@startuml
!include style.puml
skinparam ArrowFontStyle plain
skinparam sequenceReferenceBackgroundColor white


participant ":BenefitCommandParser" as BenefitCommandParser LOGIC_COLOR
participant "<<class>>\nArgumentTokenizer" as ArgumentTokenizer LOGIC_COLOR
participant "argMultimap:ArgumentMultimap" as ArgMultimap LOGIC_COLOR


-> BenefitCommandParser : parse("1 /v 150.00 /r bonus") \n or \n parse("/n Alex /v 150.00 /r bonus")
activate BenefitCommandParser

BenefitCommandParser -> ArgumentTokenizer : tokenize("1 /v 150.00 /r bonus",\nPREFIX_NAME, \nPREFIX_VALUE, \nPREFIX_REASON) \n or \n tokenize("/n Alex /v 150.00 /r bonus",\nPREFIX_NAME, \nPREFIX_VALUE, \nPREFIX_REASON)
activate ArgumentTokenizer

create ArgMultimap
ArgumentTokenizer -> ArgMultimap : new
activate ArgMultimap
ArgumentTokenizer <-- ArgMultimap
deactivate ArgMultimap
BenefitCommandParser <-- ArgumentTokenizer
deactivate ArgumentTokenizer

group **sd** Parse_Reason
end

group **sd** Parse_Value
end

group **sd** Parse_Index
end

group **sd** Parse_Name
end

<-- BenefitCommandParser : dc
deactivate BenefitCommandParser
'Hidden arrow to position the destroy marker below the end of the activation bar.
BenefitCommandParser -[hidden]->
destroy BenefitCommandParser

@enduml
