@startuml
!include style.puml
skinparam ArrowFontStyle plain

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":AddressBookParser" as AddressBookParser LOGIC_COLOR
participant ":ReadCommandParser" as ReadCommandParser LOGIC_COLOR
participant "r:ReadCommand" as ReadCommand LOGIC_COLOR
end box


[-> LogicManager : execute("read 1 /a")
activate LogicManager

LogicManager -> AddressBookParser : parseCommand("read 1 /a")
activate AddressBookParser

create ReadCommandParser
AddressBookParser -> ReadCommandParser
activate ReadCommandParser

ReadCommandParser --> AddressBookParser
deactivate ReadCommandParser

AddressBookParser -> ReadCommandParser : parse("1 /a")
activate ReadCommandParser

create ReadCommand
ReadCommandParser -> ReadCommand
activate ReadCommand

ReadCommand --> ReadCommandParser : r
deactivate ReadCommand

ReadCommandParser --> AddressBookParser : r
deactivate ReadCommandParser
'Hidden arrow to position the destroy marker below the end of the activation bar.
ReadCommandParser -[hidden]-> AddressBookParser
destroy ReadCommandParser

AddressBookParser --> LogicManager : r
deactivate AddressBookParser

@enduml
