@startuml
!include style.puml

title After down arrow press

show members

object "<u>:CommandStringStash</u>" as CommandStringStash #FFFFAA {
    currentCmdIndex = 2
}

object "<u>command0:String</u>" as cmd0 {
    value = "list - sp"
}

object "<u>command1:String</u>" as cmd1 {
    value = "help"
}

object "<u>command2:String</u>" as cmd2 {
    value = "delete 1"
}

CommandStringStash -down->cmd0
CommandStringStash-down->cmd1
CommandStringStash-down->cmd2

@end
