@startuml
skin rose
skinparam ActivityFontSize 15
skinparam ArrowFontSize 12
start
:User enters a schedule command;

:ScheduleCommandParser parses the user input and checks validity;


'Since the beta syntax does not support placing the condition outside the
'diamond we place it as the true branch instead.

switch ()
case([the schedule command is valid])
    : Creates a ScheduleCommand which is executed by Logic Manager;
    : Updates Person in FilterPersonList to have the scheduled appointment;
case([else])
    : Throws an error;
endswitch
stop
@enduml
