@startuml
'https://plantuml.com/activity-diagram-beta
|User|
skin rose
skinparam ActivityFontSize 15
skinparam ArrowFontSize 12
start
:Start JABPro;
:Enter Set command;
if () then ([Command executes successfully])
  |JABPro|
  :Set specified user to the specified status;
  |User|
  :Enter view command;
  |JABPro|
  :Show the updated user profile;
  |User|
else ([Command fails to execute])
  |JABPro|
  :Display error message and provide remedy;
  |User|

endif

stop

@enduml
