@startuml
skin rose
skinparam ActivityFontSize 15
skinparam ArrowFontSize 12

start
:User enters setP command;

if () then ([All fields to set are valid])
    if() then ([Field is of valid range])
    :Update Date Preferences;
    else([Else])
    :Command Exception is thrown;
    endif
else ([Else])
    :Command Exception is thrown;
endif

stop
@enduml
