@startuml
skin rose
skinparam ActivityFontSize 15
skinparam ArrowFontSize 12
start
:User runs show command;

'Since the beta syntax does not support placing the condition outside the
'diamond we place it as the true branch instead.

:Parse user input;

if () then ([input is valid])
    :Construct ShowCalendarCommand object;
    :Return back to LogicManager;
    :LogicManager executes ShowCalendarCommand;
    :Clear predicate of FilteredScheduleList;
    :Set predicate of FilteredCalendarScheduleList;
    :Update UI;
else ([else])
    :Display error message;
endif
stop
@enduml
