@startuml
'https://plantuml.com/activity-diagram-beta

start
:User inputs Edit Leave Command;

if () then ([else])
  :Display error message;
else ([Valid command format])
  if () then ([else])
    :Display error message;
  else ([Valid field])
    if () then ([else])
        :Display error message;
    else ([Valid order])
        : Sort all employees by specified field and order;
    endif
  endif
endif

stop

@enduml
