@startuml
skin rose
skinparam ActivityFontSize 15
skinparam ArrowFontSize 12
start
:User launches LoveBook;

: User enters a command to sort dates in the GUI;

: Input is passed over to the logic component;

if () then ([command is in the correct format with valid parameters])
        if () then ([sequence specified is increasing])
            :Display dates sorted in increasing order;
            stop
        else ([else])
            :Display dates sorted in decreasing order;
            stop
        endif
else ([else])
    :Display invalid command format error message;
    stop
endif
@enduml
