@startuml
!include style.puml
skinparam ArrowFontStyle plain

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":FlashlingoParser" as FlashlingoParser LOGIC_COLOR
participant ":SessionManager" as SessionManager LOGIC_COLOR
participant "s:StartCommand" as StartCommand LOGIC_COLOR
participant "r:CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
end box

[-> LogicManager : execute("start")
activate LogicManager

LogicManager -> FlashlingoParser : parseCommand("start")
activate FlashlingoParser

FlashlingoParser -> SessionManager : getInstance()
activate SessionManager

SessionManager -> SessionManager : SessionManager()
activate SessionManager




SessionManager --> FlashlingoParser : instance
deactivate SessionManager

FlashlingoParser -> SessionManager : isReviewSession()


SessionManager --> FlashlingoParser : isReviewSession
deactivate SessionManager


create StartCommand
FlashlingoParser -> StartCommand
activate StartCommand

StartCommand --> FlashlingoParser :
deactivate StartCommand

FlashlingoParser --> LogicManager : s
deactivate FlashlingoParser

LogicManager -> StartCommand : execute()
activate StartCommand

StartCommand -> SessionManager : setSession(true)
activate SessionManager

SessionManager --> StartCommand :
deactivate SessionManager
StartCommand -> Model : startSession()
activate Model

Model --> StartCommand
deactivate Model

create CommandResult
StartCommand -> CommandResult
activate CommandResult

CommandResult --> StartCommand
deactivate CommandResult

StartCommand --> LogicManager : r
deactivate StartCommand

[<--LogicManager
deactivate LogicManager
@enduml
