@startuml
skin rose
skinparam ActivityFontSize 15
skinparam ArrowFontSize 12

start
:User enters star command;

:Input is passed over to the logic component;
if () then ([index is present and command is valid])
    if () then ([Valid Index])
        if () then ([Date is not starred])
            :Clone the respective date object, and set it's isStarred field to True;

            :Replace date with cloned date;

            :Reset predicate to show all dates in the model;
        else ([Else])
            :Throw date is already starred error message;
        endif
    else ([Else])
        :Throw invalid index error message;
    endif
else ([Else])
    :Display invalid command format error message;
endif

stop
@enduml