
@startuml
skin rose
skinparam ActivityFontSize 15
skinparam ArrowFontSize 12

start
:User enters star command;

if () then ([Valid Index])
    if () then ([Date is not starred])
        :Apply star on date;
    else ([Else])
        :Command exception is thrown;
    endif
else ([Else])
    :Command exception is thrown;
endif

stop
@enduml
