@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor STORAGE_COLOR
skinparam classBackgroundColor STORAGE_COLOR

package Storage as StoragePackage {

Class "<<interface>>\nApplicationBookStorage" as ApplicationBookStorage
Class "<<interface>>\nStorage" as Storage
Class "<<interface>>\nUserPrefsStorage" as UserPrefsStorage
Class JsonAdaptedInterview
Class JsonAdaptedJob
Class JsonSerializableApplicationBook
Class JsonApplicationBookStorage
Class JsonUserPrefsStorage
Class StorageManager

StorageManager .up.|> Storage
StorageManager *-up-> "1" ApplicationBookStorage
StorageManager *-up-> "1" UserPrefsStorage

JsonUserPrefsStorage .down.|> UserPrefsStorage

JsonApplicationBookStorage ..|> ApplicationBookStorage
JsonApplicationBookStorage ..> JsonSerializableApplicationBook

JsonSerializableApplicationBook ..> JsonAdaptedJob
JsonAdaptedJob ..> JsonAdaptedInterview

}

@enduml
