@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor STORAGE_COLOR
skinparam classBackgroundColor STORAGE_COLOR

package Storage as StoragePackage {

package "UserPrefs Storage" #F4F6F6{
Class "<<interface>>\nUserPrefsStorage" as UserPrefsStorage
Class JsonUserPrefsStorage
}

Class "<<interface>>\nStorage" as Storage
Class StorageManager

package "NetworkBook Storage" #F4F6F6{
Class "<<interface>>\nNetworkBookStorage" as NetworkBookStorage
Class JsonNetworkBookStorage
Class JsonSerializableNetworkBook
Class JsonAdaptedPerson {
    String name
    String graduation
    String priority
}
Class "JsonAdaptedProperty<Phone>"
Class "JsonAdaptedProperty<Email>"
Class "JsonAdaptedProperty<Link>"
Class "JsonAdaptedProperty<Course>"
Class "JsonAdaptedProperty<Specialisation>"
Class "JsonAdaptedProperty<Tag>"
}

}

Class HiddenOutside #FFFFFF
HiddenOutside .r.> Storage

StorageManager .l.|> Storage
StorageManager -up-> "1" UserPrefsStorage
StorageManager -d-> "1" NetworkBookStorage

Storage -u-|> UserPrefsStorage
Storage -d-|> NetworkBookStorage

JsonUserPrefsStorage .l.|> UserPrefsStorage
JsonNetworkBookStorage .up.|> NetworkBookStorage
JsonNetworkBookStorage ..> JsonSerializableNetworkBook
JsonSerializableNetworkBook -r-> "*" JsonAdaptedPerson
JsonAdaptedPerson -u-> "*" "JsonAdaptedProperty<Phone>"
JsonAdaptedPerson -u-> "*" "JsonAdaptedProperty<Email>"
JsonAdaptedPerson -r-> "*" "JsonAdaptedProperty<Link>"
JsonAdaptedPerson -d-> "*" "JsonAdaptedProperty<Course>"
JsonAdaptedPerson -d-> "*" "JsonAdaptedProperty<Specialisation>"
JsonAdaptedPerson -d-> "*" "JsonAdaptedProperty<Tag>"

@enduml
