@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor STORAGE_COLOR
skinparam classBackgroundColor STORAGE_COLOR

package Storage as StoragePackage {

package "UserPrefs Storage" #F4F6F6 {
    Class "<<interface>>\nUserPrefsStorage" as UserPrefsStorage
    Class JsonUserPrefsStorage
}

package "ApplicationBook Storage" #F4F6F6 {
    Class "<<interface>>\nApplicationBookStorage" as ApplicationBookStorage
    Class JsonAdaptedInterview
    Class JsonAdaptedJob
    Class JsonSerializableApplicationBook
    Class JsonApplicationBookStorage
}

Class "<<interface>>\nStorage" as Storage
Class StorageManager

}

Class HiddenOutside #FFFFFF
HiddenOutside .down.> Storage
Storage -left-|> ApplicationBookStorage
Storage -right-|> UserPrefsStorage
StorageManager -up-> "1" ApplicationBookStorage
StorageManager -up-> "1" UserPrefsStorage
StorageManager .up.|> Storage
JsonApplicationBookStorage .up.|> ApplicationBookStorage
JsonApplicationBookStorage .down.> JsonSerializableApplicationBook
JsonSerializableApplicationBook -down-> "*" JsonAdaptedJob
JsonAdaptedJob -down-> "*" JsonAdaptedInterview
JsonUserPrefsStorage .up.|> UserPrefsStorage


@enduml
