@startuml
!include style.puml
skinparam ArrowFontStyle plain

Actor User as user USER_COLOR
Participant ":MainWindow" as ui UI_COLOR
Participant ":Logic" as logic LOGIC_COLOR
Participant ":Model" as model MODEL_COLOR

user -[USER_COLOR]> ui : executeCommand("theme")
activate ui UI_COLOR

ui -[UI_COLOR]> logic : execute("theme")
activate logic LOGIC_COLOR

logic -[LOGIC_COLOR]> model : toggleColorTheme()
activate model MODEL_COLOR

model -[MODEL_COLOR]-> logic
deactivate model

logic --[LOGIC_COLOR]> ui
deactivate logic
|||
ui -[UI_COLOR]> ui : handleTheme()
activate ui UI_COLOR_T1

ui -[UI_COLOR]> logic : getTheme()
activate logic LOGIC_COLOR

logic -[LOGIC_COLOR]> model : getTheme()
activate model MODEL_COLOR

model -[MODEL_COLOR]-> logic
deactivate model

logic --[LOGIC_COLOR]> ui
deactivate logic

ui -[UI_COLOR_T1]> ui : setTheme()
activate ui UI_COLOR_T2

ui--[UI_COLOR_T1]> ui
deactivate ui

ui--[UI_COLOR]> ui
deactivate ui

ui--[UI_COLOR]> user
deactivate ui
@enduml
