@startuml
!include style.puml
skinparam ArrowFontStyle plain

hide footbox
participant ":OtherClass" as OtherClass USER_COLOR

box "Logic" LOGIC_COLOR_T1
participant  "TimeParser" as TimeParser <<class>> LOGIC_COLOR
end box

OtherClass -> TimeParser: parseDate(date, false)
activate TimeParser
TimeParser -> OtherClass: Time
deactivate TimeParser
@enduml
