@startuml
skin rose
skinparam ActivityFontSize 15
skinparam ArrowFontSize 12
start
:User executes "importtransactionbook" command;
:User chooses file to import;

if () then ([Valid file format])
    :Read data from file;
    :Update Transaction Book with new data;
    :Show success message;
else ([Else])
    :Show error message;
endif

stop
@enduml
