@startuml
skin rose
skinparam ActivityFontSize 15
skinparam ArrowFontSize 12
start
:User executes "importtransactionbook" command;

if (Valid Format?) then (Yes)
    :Read Transaction Book from file;
    :Update Transaction Book as transactionbook.csv;
    :Provide Success Feedback;
else (No)
    :Provide Error Feedback;
endif

stop
@enduml
