@startuml
skin rose
skinparam ActivityFontSize 15
skinparam ArrowFontSize 12
start
:User executes "importtransactionbook" command;

if () then ([File exists and has valid format])
    :Read data from file;
    :Update Transaction Book with new data;
    :Show success message;
else ([Else])
    :Show error message;
endif

stop
@enduml
