@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor UI_COLOR_T4
skinparam classBackgroundColor UI_COLOR

package UI <<Rectangle>>{
Class "<<interface>>\nUi" as Ui
Class "{abstract}\nUiPart" as UiPart
Class UiManager
Class MainWindow
Class ResultDisplay
Class PersonListPanel
Class PersonCard
Class PersonInformationPanel
Class SummaryStatisticScreen
Class CommandBox
Class EventWindow
Class EventListPanel
Class EventCard
}

package Model <<Rectangle>> {
Class HiddenModel #FFFFFF
}

package Logic <<Rectangle>> {
Class HiddenLogic #FFFFFF
}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Ui

UiManager .left.|> Ui
UiManager -down-> "1" MainWindow
MainWindow *-down->  "1" CommandBox
MainWindow *-down-> "1" ResultDisplay
MainWindow *-down-> "1" PersonListPanel
MainWindow --> "0..1" EventWindow
EventWindow *-down-> "1" EventCard
EventWindow *-down-> "1" EventListPanel
MainWindow *-down-> "1" PersonInformationPanel
MainWindow *-down-> "1" SummaryStatisticScreen


PersonListPanel -down-> "*" PersonCard

MainWindow -left-|> UiPart

ResultDisplay --|> UiPart
CommandBox --|> UiPart
PersonInformationPanel --|> UiPart
SummaryStatisticScreen --|> UiPart
PersonListPanel --|> UiPart
PersonCard --|> UiPart



PersonInformationPanel ..> Model
SummaryStatisticScreen ..> Model
PersonCard ..> Model
UiManager -right-> Logic
MainWindow -left-> Logic
CommandBox -[hidden]left-ResultDisplay
PersonInformationPanel -[hidden]left-CommandBox
SummaryStatisticScreen -[hidden]left-PersonInformationPanel

MainWindow -[hidden]-|> UiPart
@enduml
