@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor UI_COLOR_T4
skinparam classBackgroundColor UI_COLOR

package UI <<Rectangle>>{
Class "<<interface>>\nUi" as Ui
Class "{abstract}\nUiPart" as UiPart
Class UiManager
Class MainWindow
Class HelpWindow
Class ResultDisplay
Class CardListPanel
Class DisplayCard
Class StatusBarFooter
Class CommandBox
Class GoalBox
Class ExportWindow
Class ImportWindow
}

package Model <<Rectangle>> {
Class HiddenModel #FFFFFF
}

package Logic <<Rectangle>> {
Class HiddenLogic #FFFFFF
}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Ui

UiManager .left.|> Ui
UiManager --> "1" MainWindow
MainWindow *-down-> "1" CommandBox
MainWindow *-down-> "1" ResultDisplay
MainWindow *-left-> "1" GoalBox
MainWindow *-right-> "1" CardListPanel
MainWindow *-down-> "1" StatusBarFooter
MainWindow --> "0..1" HelpWindow
MainWindow --> "0..1" ExportWindow
MainWindow --> "0..1" ImportWindow
CardListPanel -down-> "*" DisplayCard

MainWindow -right-|> UiPart

ResultDisplay --|> UiPart
CommandBox --|> UiPart
CardListPanel --|> UiPart
DisplayCard ---|> UiPart
StatusBarFooter ---|> UiPart
HelpWindow --|> UiPart
GoalBox --|> UiPart
ImportWindow --|> UiPart
ExportWindow --|> UiPart

DisplayCard ..> Model
UiManager -right-> Logic
MainWindow -left-> Logic

CardListPanel -[hidden]left- HelpWindow
HelpWindow -[hidden]left- CommandBox
ExportWindow -[hidden]left- CommandBox
ImportWindow -[hidden]left- CommandBox
CommandBox -[hidden]left- ResultDisplay
ResultDisplay -[hidden]left- StatusBarFooter

MainWindow -[hidden]-|> UiPart
@enduml
