@startuml UiClassDiagram
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor UI_COLOR_T4
skinparam classBackgroundColor UI_COLOR

package UI <<Rectangle>>{
Class "<<interface>>\nUi" as Ui
Class "{abstract}\nUiPart" as UiPart
Class UiManager
Class MainWindow
Class ResultDisplay
Class OverviewPanel
Class TransactionTablePanel
Class CardListPanel
Class PersonCard
Class CommandBox
}

package Model <<Rectangle>> {
Class HiddenModel #FFFFFF
}

package Logic <<Rectangle>> {
Class HiddenLogic #FFFFFF
}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Ui

UiManager .left.|> Ui
UiManager -down-> "1" MainWindow
MainWindow *-down->  "1" CommandBox
MainWindow *-down-> "1" ResultDisplay
MainWindow *-down-> "1" CardListPanel
MainWindow *-down-> "1" OverviewPanel
MainWindow *-down-> "1" TransactionTablePanel

CardListPanel -down-> "*" PersonCard

MainWindow -left-|> UiPart

ResultDisplay --|> UiPart
CommandBox --|> UiPart
CardListPanel --|> UiPart
PersonCard --|> UiPart
OverviewPanel --|> UiPart
TransactionTablePanel --|> UiPart

PersonCard ..> Model
OverviewPanel ..> Model
TransactionTablePanel ..> Model
UiManager -right-> Logic
MainWindow -left-> Logic

CommandBox -[hidden]left- ResultDisplay

MainWindow -[hidden]-|> UiPart
@enduml
