@startuml
!include style.puml
skinparam ArrowFontStyle plain

box LOGIC_COLOR_T1
participant ":FlashcardBox" as FlashcardBox LOGIC_COLOR
participant ":MainWindow" as MainWindow LOGIC_COLOR
participant "logic:Logic" as Logic LOGIC_COLOR
participant ":FlashlingoParser" as FlashlingoParser LOGIC_COLOR
participant "command:YesCommand" as YesCommand LOGIC_COLOR
participant ":CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
end box

[-> FlashcardBox : success()
activate FlashcardBox


FlashcardBox -> MainWindow : executeCommand("no")
activate MainWindow

MainWindow -> Logic : executeCommand("no")
activate Logic

Logic -> FlashlingoParser : parseCommand("no")
activate FlashlingoParser
return command

Logic -> YesCommand : execute(<<model>>)
activate YesCommand
YesCommand -> Model : rememberWord(false)
activate Model

return
return commandResult
return commandResult

MainWindow -> CommandResult : getFeedbackToUser()
activate CommandResult
return


MainWindow --> FlashcardBox
deactivate MainWindow
<--FlashcardBox
deactivate FlashcardBox
@enduml
