@startuml
!include style.puml
skinparam ClassFontColor #000000
skinparam ClassBorderColor #000000
skinparam ClassBackgroundColor #FFFFAA

title After command "delete 5"

package UndoList {
    class State0 as "<u>ab0:AddressBook</u>"
}

package RedoList {
}

package CurrentState {
    class State1 as "<u>ab1:AddressBook</u>"
}
@end
