@startuml
!include style.puml
skinparam ArrowFontStyle plain

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":LoveBookParser" as LoveBookParser LOGIC_COLOR
participant "u:UndoCommand" as UndoCommand LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
participant ":VersionedLoveBook" as VersionedLoveBook MODEL_COLOR
end box
[-> LogicManager : execute(undo)
activate LogicManager

LogicManager -> LoveBookParser : parseCommand(undo)
activate LoveBookParser

create UndoCommand
LoveBookParser -> UndoCommand
activate UndoCommand

UndoCommand --> LoveBookParser
deactivate UndoCommand

LoveBookParser --> LogicManager : u
deactivate LoveBookParser

LogicManager -> UndoCommand : execute()
activate UndoCommand

UndoCommand -> Model : undoLoveBook()
activate Model

Model -> VersionedLoveBook : undo()
activate VersionedLoveBook

VersionedLoveBook -> VersionedLoveBook :resetData(ReadOnlyLoveBook)
VersionedLoveBook --> Model :
deactivate VersionedLoveBook

Model --> UndoCommand
deactivate Model

UndoCommand --> LogicManager : result
deactivate UndoCommand
UndoCommand -[hidden]-> LogicManager : result
destroy UndoCommand

[<--LogicManager
deactivate LogicManager
@enduml
