@startuml
!include style.puml
skinparam ClassFontColor #000000
skinparam ClassBorderColor #000000
skinparam ClassBackgroundColor #FFFFAA

title Initial state

package UndoList {
}

package RedoList {
}

package CurrentState {
    class State0 as "<u>ab0:AddressBook</u>"
}
@end
