@startuml
!include style.puml
skinparam ClassFontColor #000000
skinparam ClassBorderColor #000000
skinparam ClassBackgroundColor #FFFFAA

title After command "undo"

package RedoList {
    class State2 as "<u>ab2:AddressBook</u>"
}

package UndoList {
    class State0 as "<u>ab0:AddressBook</u>"
}

package CurrentState {
    class State1 as "<u>ab1:AddressBook</u>"
}
@end
