@startuml
skin rose
skinparam ActivityFontSize 15
skinparam ArrowFontSize 12

start
:User executes command;

if () then ([command commits AddressBook])
    :Retrieve command history from model;
    if () then ([valid number of undo steps?])
        :Execute Undo;
    else ([else])
    endif
else ([else]))
endif
stop

@enduml

