@startuml
!include style.puml
skinparam ArrowFontStyle plain

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":NetworkBookParser" as NetworkBookParser LOGIC_COLOR
participant "u:UndoCommand" as UndoCommand LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
participant ":VersionedNetworkBook" as VersionedNetworkBook MODEL_COLOR
end box
[-> LogicManager : execute("undo")
activate LogicManager

LogicManager -> NetworkBookParser : parseCommand("undo")
activate NetworkBookParser

create UndoCommand
NetworkBookParser -> UndoCommand : new UndoCommand()
activate UndoCommand

UndoCommand --> NetworkBookParser
deactivate UndoCommand

NetworkBookParser --> LogicManager : u
deactivate NetworkBookParser

LogicManager -> UndoCommand : execute()
activate UndoCommand

UndoCommand -> Model : undoNetworkBook()
activate Model

Model -> VersionedNetworkBook : undo()
activate VersionedNetworkBook

VersionedNetworkBook -> VersionedNetworkBook :resetData(previousData)
VersionedNetworkBook --> Model :
deactivate VersionedNetworkBook

Model --> UndoCommand
deactivate Model

UndoCommand --> LogicManager : command success
deactivate UndoCommand
UndoCommand -[hidden]-> LogicManager : command success
destroy UndoCommand

[<--LogicManager
deactivate LogicManager
@enduml
