
@startuml
skin rose
skinparam ActivityFontSize 15
skinparam ArrowFontSize 12

start
:User enters unstar command;

if () then ([Valid Index])
    if () then ([Date is starred])
        :Apply unstar on date;
    else ([Else])
        :Command exception is thrown;
    endif
else ([Else])
    :Command exception is thrown;
endif

stop
@enduml
