@startuml
skin rose
skinparam ActivityFontSize 15
skinparam ArrowFontSize 12
start
:User presses up arrow;

'Since the beta syntax does not support placing the condition outside the
'diamond we place it as the true branch instead.

if (Command String Stash is empty OR
currentCmdIndex points to the
least recently added command ?) then ([no])
    :decrement currentCmdIndex;
    :return the command string
    pointed to by currentCmdIndex ;
else ([yes])
    :return the command string
    currently in the CLI textbox ;
endif
stop
@enduml
