@startuml
skin rose
skinparam ActivityFontSize 15
skinparam ArrowFontSize 12
start
:User inputs view command;

'Since the beta syntax does not support placing the condition outside the
'diamond we place it as the true branch instead.

if () then ([valid index])
    :view command executed;
    :UI update the ViewPersonPanel
              in the main window;
else ([else])
    :Show error and usage message;
endif
stop
@enduml
