@startuml
skin rose
skinparam ActivityFontSize 15
skinparam ArrowFontSize 12
start
:User enters command to view an applicant;

if () then ([invalid command])
    : Invalid command error message is shown;
else ([else])
    if () then ([invalid applicant])
        : Invalid Applicant Index error message is shown;
    else ([else])
        : Update the applicant list in the GUI;
        :Success message is shown;
    endif
endif
stop
@enduml
