@startuml
!include style.puml
skinparam ArrowFontStyle plain

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":FlashlingoParser" as FlashlingoParser LOGIC_COLOR
participant "s:YesCommand" as YesCommand LOGIC_COLOR
participant ":SessionManager" as SessionManager LOGIC_COLOR
participant "s:CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
participant ":FlashCard" as FlashCard MODEL_COLOR
end box

[-> LogicManager : execute("yes")
activate LogicManager

LogicManager -> FlashlingoParser : parseCommand("yes")
activate FlashlingoParser

create YesCommand
FlashlingoParser -> YesCommand : Create instance
activate YesCommand


YesCommand -> Model: nextReviewWord()
activate Model
YesCommand -> FlashCard: updateLevel(true)
activate FlashCard
YesCommand -> FlashCard: recallFlashCard()
deactivate FlashCard
YesCommand -> Model: hasNextRound()

alt No more words to review
    YesCommand -> SessionManager: setSession(false)
    activate SessionManager
    SessionManager -> Model: updateFilteredFlashCardList()
    deactivate SessionManager
    create CommandResult
    YesCommand -> CommandResult : CommandResult()
    activate CommandResult
    CommandResult --> LogicManager : return CommandResult
    deactivate CommandResult
else More words to review
    YesCommand -> Model: nextReviewWord()
    deactivate Model
    create CommandResult
    YesCommand -> CommandResult : CommandResult()
    activate CommandResult
    CommandResult --> LogicManager : return CommandResult
    deactivate CommandResult
end

deactivate FlashlingoParser

[<--LogicManager
deactivate LogicManager
@enduml
