@startuml
!include ../style.puml
skinparam ArrowFontStyle plain

box Logic #skyblue
Participant ":FindCommand" as fc LOGIC_COLOR
Participant ":CommandResult" as cr LOGIC_COLOR
end box
box Model #pink
Participant "model:Model" as m MODEL_COLOR
end box

[-> fc ++: execute()
fc -> m ++: updateFilteredJobList()
deactivate m
create cr
fc -> cr ++: CommandResult()
cr --> fc --: result
fc -->[ --: result
@enduml
