@startuml
!include ../style.puml
skinparam ArrowFontStyle plain

box Logic LOGIC_COLOR_T1
Participant ":InterviewEditCommand" as iec LOGIC_COLOR
Participant "result:CommandResult" as cr LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
Participant "model:Model" as m MODEL_COLOR
Participant "jobToEditInterview:Job" as j MODEL_COLOR
end box

[-> iec ++: execute()
iec -> m ++: getJob()
m --> iec--: jobToEditInterview
iec -> j ++: getInterview()
j --> iec--: interviewToEdit
iec -> j ++: setInterview()
deactivate j
create cr
iec -> cr ++
cr --> iec --
iec -->[ --: result

@enduml
