@startuml
!include ../style.puml
skinparam ArrowFontStyle plain

Participant ":InterviewDeleteCommandParser" as idcp LOGIC_COLOR
Participant "<<class>>\nArgumentTokenizer" as at LOGIC_COLOR
Participant "<<class>>\nParserUtil" as pu LOGIC_COLOR
Participant "command:InterviewDeleteCommand" as idc LOGIC_COLOR

[-> idcp ++: parse(args)
idcp -> at ++: tokenize user input
at --> idcp --: argMultimap

idcp -> pu ++: parseIndex()
pu --> idcp --: interviewIndex

idcp -> pu ++: parseIndex()
pu --> idcp --: jobIndex

create idc
idcp -> idc ++: InterviewDeleteCommand(jobIndex, interviewIndex)
idc --> idcp --
idcp -->[ --: command
@enduml
