@startuml
!include ../style.puml
skinparam ArrowFontStyle plain

title View Contact Command Sequence

Participant ":LogicManager" as logic LOGIC_COLOR
Participant ":AddressBookParser" as abp LOGIC_COLOR
Participant ":ViewContactCommandParser" as vccp LOGIC_COLOR
Participant "command:ViewContactCommand" as ec LOGIC_COLOR

[-> logic : execute
activate logic
logic -> abp ++: parseCommand(commandText)
create vccp
abp -> vccp
abp -> vccp ++: parse(arguments)
create ec
vccp -> ec ++: index
ec --> vccp --
vccp --> abp --: command
abp --> logic --: command

@enduml
