@startuml
!include ../style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

Employee --> "*" DepartmentName
Employee *--> Phone
Employee *--> Address
Employee *--> Email
Employee *--> Salary
Employee *--> Leave
Employee *--> Role
Employee *--> EmployeeName : name
Employee --> "*" EmployeeName : superiors

@enduml