name: Shell Script Checks

on: [push, pull_request]


jobs:
  run-shell-scripts:
    strategy:
      matrix:
        platform: [ ubuntu-latest, macos-latest, windows-latest ]
    runs-on: ${{ matrix.platform }}

    steps:
      - name: Set up repository
        uses: actions/checkout@main

      - name: Set up repository
        uses: actions/checkout@main
        with:
          ref: master

      - name: Checkout triggering commit
        run: git checkout --progress --force ${{ github.sha }}

      - name: Run repository-wide tests
        working-directory:  ${{ github.workspace }}/.github
        run: ./run-checks.sh
